# Generated by Django 3.2.9 on 2021-12-14 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Alpha', 'A'), ('Beta', 'B'), ('Classy', 'C'), ('Luxury', 'L')], max_length=25)),
                ('price', models.PositiveIntegerField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numofbeds', models.PositiveIntegerField()),
                ('numofbath', models.PositiveIntegerField()),
                ('numofgarage', models.CharField(max_length=10)),
                ('photo', models.ImageField(null=True, upload_to='rooms')),
                ('roomdetail', models.TextField(default=True, max_length=255)),
                ('categories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.categories')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('checkin', models.DateField()),
                ('checkout', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(default='0', max_length=10)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.properties')),
            ],
        ),
    ]
