# Generated by Django 3.2.9 on 2021-12-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20211220_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_created',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(default='+233', max_length=10),
        ),
    ]
