# Generated by Django 3.2.9 on 2021-12-21 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20211221_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='is_created',
        ),
    ]
