# Generated by Django 3.2.9 on 2021-12-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_reservation_is_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(default='+233', max_length=13),
        ),
    ]
